/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AAndAndExp extends PAndExp
{
    private PAndExp _left_;
    private TAnd _and_;
    private PCmpExp _right_;

    public AAndAndExp()
    {
    }

    public AAndAndExp(
        PAndExp _left_,
        TAnd _and_,
        PCmpExp _right_)
    {
        setLeft(_left_);

        setAnd(_and_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AAndAndExp(
            (PAndExp) cloneNode(_left_),
            (TAnd) cloneNode(_and_),
            (PCmpExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndAndExp(this);
    }

    public PAndExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PAndExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TAnd getAnd()
    {
        return _and_;
    }

    public void setAnd(TAnd node)
    {
        if(_and_ != null)
        {
            _and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _and_ = node;
    }

    public PCmpExp getRight()
    {
        return _right_;
    }

    public void setRight(PCmpExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_and_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_and_ == child)
        {
            _and_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PAndExp) newChild);
            return;
        }

        if(_and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PCmpExp) newChild);
            return;
        }

    }
}
