/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AAssignExp extends PExp
{
    private PLvalue _lvalue_;
    private TAssign _assign_;
    private POrExp _orExp_;

    public AAssignExp()
    {
    }

    public AAssignExp(
        PLvalue _lvalue_,
        TAssign _assign_,
        POrExp _orExp_)
    {
        setLvalue(_lvalue_);

        setAssign(_assign_);

        setOrExp(_orExp_);

    }
    public Object clone()
    {
        return new AAssignExp(
            (PLvalue) cloneNode(_lvalue_),
            (TAssign) cloneNode(_assign_),
            (POrExp) cloneNode(_orExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignExp(this);
    }

    public PLvalue getLvalue()
    {
        return _lvalue_;
    }

    public void setLvalue(PLvalue node)
    {
        if(_lvalue_ != null)
        {
            _lvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lvalue_ = node;
    }

    public TAssign getAssign()
    {
        return _assign_;
    }

    public void setAssign(TAssign node)
    {
        if(_assign_ != null)
        {
            _assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _assign_ = node;
    }

    public POrExp getOrExp()
    {
        return _orExp_;
    }

    public void setOrExp(POrExp node)
    {
        if(_orExp_ != null)
        {
            _orExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _orExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lvalue_)
            + toString(_assign_)
            + toString(_orExp_);
    }

    void removeChild(Node child)
    {
        if(_lvalue_ == child)
        {
            _lvalue_ = null;
            return;
        }

        if(_assign_ == child)
        {
            _assign_ = null;
            return;
        }

        if(_orExp_ == child)
        {
            _orExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lvalue_ == oldChild)
        {
            setLvalue((PLvalue) newChild);
            return;
        }

        if(_assign_ == oldChild)
        {
            setAssign((TAssign) newChild);
            return;
        }

        if(_orExp_ == oldChild)
        {
            setOrExp((POrExp) newChild);
            return;
        }

    }
}
