/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AAssignAttribute extends PAttribute
{
    private PAttr _leftAttr_;
    private TAssign _assign_;
    private PAttr _rightAttr_;

    public AAssignAttribute()
    {
    }

    public AAssignAttribute(
        PAttr _leftAttr_,
        TAssign _assign_,
        PAttr _rightAttr_)
    {
        setLeftAttr(_leftAttr_);

        setAssign(_assign_);

        setRightAttr(_rightAttr_);

    }
    public Object clone()
    {
        return new AAssignAttribute(
            (PAttr) cloneNode(_leftAttr_),
            (TAssign) cloneNode(_assign_),
            (PAttr) cloneNode(_rightAttr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignAttribute(this);
    }

    public PAttr getLeftAttr()
    {
        return _leftAttr_;
    }

    public void setLeftAttr(PAttr node)
    {
        if(_leftAttr_ != null)
        {
            _leftAttr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _leftAttr_ = node;
    }

    public TAssign getAssign()
    {
        return _assign_;
    }

    public void setAssign(TAssign node)
    {
        if(_assign_ != null)
        {
            _assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _assign_ = node;
    }

    public PAttr getRightAttr()
    {
        return _rightAttr_;
    }

    public void setRightAttr(PAttr node)
    {
        if(_rightAttr_ != null)
        {
            _rightAttr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rightAttr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_leftAttr_)
            + toString(_assign_)
            + toString(_rightAttr_);
    }

    void removeChild(Node child)
    {
        if(_leftAttr_ == child)
        {
            _leftAttr_ = null;
            return;
        }

        if(_assign_ == child)
        {
            _assign_ = null;
            return;
        }

        if(_rightAttr_ == child)
        {
            _rightAttr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_leftAttr_ == oldChild)
        {
            setLeftAttr((PAttr) newChild);
            return;
        }

        if(_assign_ == oldChild)
        {
            setAssign((TAssign) newChild);
            return;
        }

        if(_rightAttr_ == oldChild)
        {
            setRightAttr((PAttr) newChild);
            return;
        }

    }
}
