/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AAttributeInputattr extends PInputattr
{
    private PAttribute _attribute_;

    public AAttributeInputattr()
    {
    }

    public AAttributeInputattr(
        PAttribute _attribute_)
    {
        setAttribute(_attribute_);

    }
    public Object clone()
    {
        return new AAttributeInputattr(
            (PAttribute) cloneNode(_attribute_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributeInputattr(this);
    }

    public PAttribute getAttribute()
    {
        return _attribute_;
    }

    public void setAttribute(PAttribute node)
    {
        if(_attribute_ != null)
        {
            _attribute_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _attribute_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_attribute_);
    }

    void removeChild(Node child)
    {
        if(_attribute_ == child)
        {
            _attribute_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_attribute_ == oldChild)
        {
            setAttribute((PAttribute) newChild);
            return;
        }

    }
}
