/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ACompStmNoShortIf extends PStmNoShortIf
{
    private PCompoundstm _compoundstm_;

    public ACompStmNoShortIf()
    {
    }

    public ACompStmNoShortIf(
        PCompoundstm _compoundstm_)
    {
        setCompoundstm(_compoundstm_);

    }
    public Object clone()
    {
        return new ACompStmNoShortIf(
            (PCompoundstm) cloneNode(_compoundstm_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompStmNoShortIf(this);
    }

    public PCompoundstm getCompoundstm()
    {
        return _compoundstm_;
    }

    public void setCompoundstm(PCompoundstm node)
    {
        if(_compoundstm_ != null)
        {
            _compoundstm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _compoundstm_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_compoundstm_);
    }

    void removeChild(Node child)
    {
        if(_compoundstm_ == child)
        {
            _compoundstm_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_compoundstm_ == oldChild)
        {
            setCompoundstm((PCompoundstm) newChild);
            return;
        }

    }
}
