/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ADefaultAddExp extends PAddExp
{
    private PMultExp _multExp_;

    public ADefaultAddExp()
    {
    }

    public ADefaultAddExp(
        PMultExp _multExp_)
    {
        setMultExp(_multExp_);

    }
    public Object clone()
    {
        return new ADefaultAddExp(
            (PMultExp) cloneNode(_multExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultAddExp(this);
    }

    public PMultExp getMultExp()
    {
        return _multExp_;
    }

    public void setMultExp(PMultExp node)
    {
        if(_multExp_ != null)
        {
            _multExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_multExp_);
    }

    void removeChild(Node child)
    {
        if(_multExp_ == child)
        {
            _multExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_multExp_ == oldChild)
        {
            setMultExp((PMultExp) newChild);
            return;
        }

    }
}
