/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ADefaultExp extends PExp
{
    private POrExp _orExp_;

    public ADefaultExp()
    {
    }

    public ADefaultExp(
        POrExp _orExp_)
    {
        setOrExp(_orExp_);

    }
    public Object clone()
    {
        return new ADefaultExp(
            (POrExp) cloneNode(_orExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultExp(this);
    }

    public POrExp getOrExp()
    {
        return _orExp_;
    }

    public void setOrExp(POrExp node)
    {
        if(_orExp_ != null)
        {
            _orExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _orExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_orExp_);
    }

    void removeChild(Node child)
    {
        if(_orExp_ == child)
        {
            _orExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_orExp_ == oldChild)
        {
            setOrExp((POrExp) newChild);
            return;
        }

    }
}
