/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ADefaultMultExp extends PMultExp
{
    private PJoinExp _joinExp_;

    public ADefaultMultExp()
    {
    }

    public ADefaultMultExp(
        PJoinExp _joinExp_)
    {
        setJoinExp(_joinExp_);

    }
    public Object clone()
    {
        return new ADefaultMultExp(
            (PJoinExp) cloneNode(_joinExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultMultExp(this);
    }

    public PJoinExp getJoinExp()
    {
        return _joinExp_;
    }

    public void setJoinExp(PJoinExp node)
    {
        if(_joinExp_ != null)
        {
            _joinExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _joinExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_joinExp_);
    }

    void removeChild(Node child)
    {
        if(_joinExp_ == child)
        {
            _joinExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_joinExp_ == oldChild)
        {
            setJoinExp((PJoinExp) newChild);
            return;
        }

    }
}
