/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ADefaultAndExp extends PAndExp
{
    private PCmpExp _cmpExp_;

    public ADefaultAndExp()
    {
    }

    public ADefaultAndExp(
        PCmpExp _cmpExp_)
    {
        setCmpExp(_cmpExp_);

    }
    public Object clone()
    {
        return new ADefaultAndExp(
            (PCmpExp) cloneNode(_cmpExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultAndExp(this);
    }

    public PCmpExp getCmpExp()
    {
        return _cmpExp_;
    }

    public void setCmpExp(PCmpExp node)
    {
        if(_cmpExp_ != null)
        {
            _cmpExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _cmpExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_cmpExp_);
    }

    void removeChild(Node child)
    {
        if(_cmpExp_ == child)
        {
            _cmpExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_cmpExp_ == oldChild)
        {
            setCmpExp((PCmpExp) newChild);
            return;
        }

    }
}
