/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ADefaultOrExp extends POrExp
{
    private PAndExp _andExp_;

    public ADefaultOrExp()
    {
    }

    public ADefaultOrExp(
        PAndExp _andExp_)
    {
        setAndExp(_andExp_);

    }
    public Object clone()
    {
        return new ADefaultOrExp(
            (PAndExp) cloneNode(_andExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultOrExp(this);
    }

    public PAndExp getAndExp()
    {
        return _andExp_;
    }

    public void setAndExp(PAndExp node)
    {
        if(_andExp_ != null)
        {
            _andExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _andExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_andExp_);
    }

    void removeChild(Node child)
    {
        if(_andExp_ == child)
        {
            _andExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_andExp_ == oldChild)
        {
            setAndExp((PAndExp) newChild);
            return;
        }

    }
}
