/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ADivMultExp extends PMultExp
{
    private PMultExp _left_;
    private TDiv _div_;
    private PJoinExp _right_;

    public ADivMultExp()
    {
    }

    public ADivMultExp(
        PMultExp _left_,
        TDiv _div_,
        PJoinExp _right_)
    {
        setLeft(_left_);

        setDiv(_div_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new ADivMultExp(
            (PMultExp) cloneNode(_left_),
            (TDiv) cloneNode(_div_),
            (PJoinExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivMultExp(this);
    }

    public PMultExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PMultExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TDiv getDiv()
    {
        return _div_;
    }

    public void setDiv(TDiv node)
    {
        if(_div_ != null)
        {
            _div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _div_ = node;
    }

    public PJoinExp getRight()
    {
        return _right_;
    }

    public void setRight(PJoinExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_div_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_div_ == child)
        {
            _div_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PMultExp) newChild);
            return;
        }

        if(_div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PJoinExp) newChild);
            return;
        }

    }
}
