/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AEqCmpExp extends PCmpExp
{
    private PAddExp _left_;
    private TEq _eq_;
    private PAddExp _right_;

    public AEqCmpExp()
    {
    }

    public AEqCmpExp(
        PAddExp _left_,
        TEq _eq_,
        PAddExp _right_)
    {
        setLeft(_left_);

        setEq(_eq_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AEqCmpExp(
            (PAddExp) cloneNode(_left_),
            (TEq) cloneNode(_eq_),
            (PAddExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqCmpExp(this);
    }

    public PAddExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PAddExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TEq getEq()
    {
        return _eq_;
    }

    public void setEq(TEq node)
    {
        if(_eq_ != null)
        {
            _eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eq_ = node;
    }

    public PAddExp getRight()
    {
        return _right_;
    }

    public void setRight(PAddExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_eq_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_eq_ == child)
        {
            _eq_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PAddExp) newChild);
            return;
        }

        if(_eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PAddExp) newChild);
            return;
        }

    }
}
