/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AExitStm extends PStm
{
    private TExit _exit_;
    private PDocument _document_;
    private TSemicolon _semicolon_;

    public AExitStm()
    {
    }

    public AExitStm(
        TExit _exit_,
        PDocument _document_,
        TSemicolon _semicolon_)
    {
        setExit(_exit_);

        setDocument(_document_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AExitStm(
            (TExit) cloneNode(_exit_),
            (PDocument) cloneNode(_document_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExitStm(this);
    }

    public TExit getExit()
    {
        return _exit_;
    }

    public void setExit(TExit node)
    {
        if(_exit_ != null)
        {
            _exit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exit_ = node;
    }

    public PDocument getDocument()
    {
        return _document_;
    }

    public void setDocument(PDocument node)
    {
        if(_document_ != null)
        {
            _document_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _document_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exit_)
            + toString(_document_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_exit_ == child)
        {
            _exit_ = null;
            return;
        }

        if(_document_ == child)
        {
            _document_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exit_ == oldChild)
        {
            setExit((TExit) newChild);
            return;
        }

        if(_document_ == oldChild)
        {
            setDocument((PDocument) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
