/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AFunction extends PFunction
{
    private PType _type_;
    private TIdentifier _identifier_;
    private TLPar _lPar_;
    private PArguments _arguments_;
    private TRPar _rPar_;
    private PCompoundstm _compoundstm_;

    public AFunction()
    {
    }

    public AFunction(
        PType _type_,
        TIdentifier _identifier_,
        TLPar _lPar_,
        PArguments _arguments_,
        TRPar _rPar_,
        PCompoundstm _compoundstm_)
    {
        setType(_type_);

        setIdentifier(_identifier_);

        setLPar(_lPar_);

        setArguments(_arguments_);

        setRPar(_rPar_);

        setCompoundstm(_compoundstm_);

    }
    public Object clone()
    {
        return new AFunction(
            (PType) cloneNode(_type_),
            (TIdentifier) cloneNode(_identifier_),
            (TLPar) cloneNode(_lPar_),
            (PArguments) cloneNode(_arguments_),
            (TRPar) cloneNode(_rPar_),
            (PCompoundstm) cloneNode(_compoundstm_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunction(this);
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PArguments getArguments()
    {
        return _arguments_;
    }

    public void setArguments(PArguments node)
    {
        if(_arguments_ != null)
        {
            _arguments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _arguments_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PCompoundstm getCompoundstm()
    {
        return _compoundstm_;
    }

    public void setCompoundstm(PCompoundstm node)
    {
        if(_compoundstm_ != null)
        {
            _compoundstm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _compoundstm_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_type_)
            + toString(_identifier_)
            + toString(_lPar_)
            + toString(_arguments_)
            + toString(_rPar_)
            + toString(_compoundstm_);
    }

    void removeChild(Node child)
    {
        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_arguments_ == child)
        {
            _arguments_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_compoundstm_ == child)
        {
            _compoundstm_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_arguments_ == oldChild)
        {
            setArguments((PArguments) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_compoundstm_ == oldChild)
        {
            setCompoundstm((PCompoundstm) newChild);
            return;
        }

    }
}
