/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AGteqCmpExp extends PCmpExp
{
    private PAddExp _left_;
    private TGteq _gteq_;
    private PAddExp _right_;

    public AGteqCmpExp()
    {
    }

    public AGteqCmpExp(
        PAddExp _left_,
        TGteq _gteq_,
        PAddExp _right_)
    {
        setLeft(_left_);

        setGteq(_gteq_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AGteqCmpExp(
            (PAddExp) cloneNode(_left_),
            (TGteq) cloneNode(_gteq_),
            (PAddExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGteqCmpExp(this);
    }

    public PAddExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PAddExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TGteq getGteq()
    {
        return _gteq_;
    }

    public void setGteq(TGteq node)
    {
        if(_gteq_ != null)
        {
            _gteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gteq_ = node;
    }

    public PAddExp getRight()
    {
        return _right_;
    }

    public void setRight(PAddExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_gteq_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_gteq_ == child)
        {
            _gteq_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PAddExp) newChild);
            return;
        }

        if(_gteq_ == oldChild)
        {
            setGteq((TGteq) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PAddExp) newChild);
            return;
        }

    }
}
