/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AHoleHtmlbody extends PHtmlbody
{
    private TLtBracket _ltBracket_;
    private TIdentifier _identifier_;
    private TGtBracket _gtBracket_;

    public AHoleHtmlbody()
    {
    }

    public AHoleHtmlbody(
        TLtBracket _ltBracket_,
        TIdentifier _identifier_,
        TGtBracket _gtBracket_)
    {
        setLtBracket(_ltBracket_);

        setIdentifier(_identifier_);

        setGtBracket(_gtBracket_);

    }
    public Object clone()
    {
        return new AHoleHtmlbody(
            (TLtBracket) cloneNode(_ltBracket_),
            (TIdentifier) cloneNode(_identifier_),
            (TGtBracket) cloneNode(_gtBracket_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHoleHtmlbody(this);
    }

    public TLtBracket getLtBracket()
    {
        return _ltBracket_;
    }

    public void setLtBracket(TLtBracket node)
    {
        if(_ltBracket_ != null)
        {
            _ltBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ltBracket_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TGtBracket getGtBracket()
    {
        return _gtBracket_;
    }

    public void setGtBracket(TGtBracket node)
    {
        if(_gtBracket_ != null)
        {
            _gtBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gtBracket_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_ltBracket_)
            + toString(_identifier_)
            + toString(_gtBracket_);
    }

    void removeChild(Node child)
    {
        if(_ltBracket_ == child)
        {
            _ltBracket_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_gtBracket_ == child)
        {
            _gtBracket_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_ltBracket_ == oldChild)
        {
            setLtBracket((TLtBracket) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_gtBracket_ == oldChild)
        {
            setGtBracket((TGtBracket) newChild);
            return;
        }

    }
}
