/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AInputHtmlbody extends PHtmlbody
{
    private TLt _lt_;
    private TInput _input_;
    private final LinkedList _inputattr_ = new TypedLinkedList(new Inputattr_Cast());
    private TGt _gt_;

    public AInputHtmlbody()
    {
    }

    public AInputHtmlbody(
        TLt _lt_,
        TInput _input_,
        List _inputattr_,
        TGt _gt_)
    {
        setLt(_lt_);

        setInput(_input_);

        {
            this._inputattr_.clear();
            this._inputattr_.addAll(_inputattr_);
        }

        setGt(_gt_);

    }
    public Object clone()
    {
        return new AInputHtmlbody(
            (TLt) cloneNode(_lt_),
            (TInput) cloneNode(_input_),
            cloneList(_inputattr_),
            (TGt) cloneNode(_gt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInputHtmlbody(this);
    }

    public TLt getLt()
    {
        return _lt_;
    }

    public void setLt(TLt node)
    {
        if(_lt_ != null)
        {
            _lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lt_ = node;
    }

    public TInput getInput()
    {
        return _input_;
    }

    public void setInput(TInput node)
    {
        if(_input_ != null)
        {
            _input_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _input_ = node;
    }

    public LinkedList getInputattr()
    {
        return _inputattr_;
    }

    public void setInputattr(List list)
    {
        _inputattr_.clear();
        _inputattr_.addAll(list);
    }

    public TGt getGt()
    {
        return _gt_;
    }

    public void setGt(TGt node)
    {
        if(_gt_ != null)
        {
            _gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lt_)
            + toString(_input_)
            + toString(_inputattr_)
            + toString(_gt_);
    }

    void removeChild(Node child)
    {
        if(_lt_ == child)
        {
            _lt_ = null;
            return;
        }

        if(_input_ == child)
        {
            _input_ = null;
            return;
        }

        if(_inputattr_.remove(child))
        {
            return;
        }

        if(_gt_ == child)
        {
            _gt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(_input_ == oldChild)
        {
            setInput((TInput) newChild);
            return;
        }

        for(ListIterator i = _inputattr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

    }

    private class Inputattr_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PInputattr node = (PInputattr) o;

            if((node.parent() != null) &&
                (node.parent() != AInputHtmlbody.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AInputHtmlbody.this))
            {
                node.parent(AInputHtmlbody.this);
            }

            return node;
        }
    }
}
