/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AIntAttr extends PAttr
{
    private TIntconst _intconst_;

    public AIntAttr()
    {
    }

    public AIntAttr(
        TIntconst _intconst_)
    {
        setIntconst(_intconst_);

    }
    public Object clone()
    {
        return new AIntAttr(
            (TIntconst) cloneNode(_intconst_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntAttr(this);
    }

    public TIntconst getIntconst()
    {
        return _intconst_;
    }

    public void setIntconst(TIntconst node)
    {
        if(_intconst_ != null)
        {
            _intconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _intconst_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_intconst_);
    }

    void removeChild(Node child)
    {
        if(_intconst_ == child)
        {
            _intconst_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_intconst_ == oldChild)
        {
            setIntconst((TIntconst) newChild);
            return;
        }

    }
}
