/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AKeepManyTupleExp extends PTupleExp
{
    private PTupleExp _tupleExp_;
    private TKeep _keep_;
    private TLPar _lPar_;
    private PIdentifiers _identifiers_;
    private TRPar _rPar_;

    public AKeepManyTupleExp()
    {
    }

    public AKeepManyTupleExp(
        PTupleExp _tupleExp_,
        TKeep _keep_,
        TLPar _lPar_,
        PIdentifiers _identifiers_,
        TRPar _rPar_)
    {
        setTupleExp(_tupleExp_);

        setKeep(_keep_);

        setLPar(_lPar_);

        setIdentifiers(_identifiers_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new AKeepManyTupleExp(
            (PTupleExp) cloneNode(_tupleExp_),
            (TKeep) cloneNode(_keep_),
            (TLPar) cloneNode(_lPar_),
            (PIdentifiers) cloneNode(_identifiers_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeepManyTupleExp(this);
    }

    public PTupleExp getTupleExp()
    {
        return _tupleExp_;
    }

    public void setTupleExp(PTupleExp node)
    {
        if(_tupleExp_ != null)
        {
            _tupleExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tupleExp_ = node;
    }

    public TKeep getKeep()
    {
        return _keep_;
    }

    public void setKeep(TKeep node)
    {
        if(_keep_ != null)
        {
            _keep_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keep_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PIdentifiers getIdentifiers()
    {
        return _identifiers_;
    }

    public void setIdentifiers(PIdentifiers node)
    {
        if(_identifiers_ != null)
        {
            _identifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifiers_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tupleExp_)
            + toString(_keep_)
            + toString(_lPar_)
            + toString(_identifiers_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_tupleExp_ == child)
        {
            _tupleExp_ = null;
            return;
        }

        if(_keep_ == child)
        {
            _keep_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_identifiers_ == child)
        {
            _identifiers_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tupleExp_ == oldChild)
        {
            setTupleExp((PTupleExp) newChild);
            return;
        }

        if(_keep_ == oldChild)
        {
            setKeep((TKeep) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_identifiers_ == oldChild)
        {
            setIdentifiers((PIdentifiers) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
