/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AKeepTupleExp extends PTupleExp
{
    private PTupleExp _tupleExp_;
    private TKeep _keep_;
    private TIdentifier _identifier_;

    public AKeepTupleExp()
    {
    }

    public AKeepTupleExp(
        PTupleExp _tupleExp_,
        TKeep _keep_,
        TIdentifier _identifier_)
    {
        setTupleExp(_tupleExp_);

        setKeep(_keep_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new AKeepTupleExp(
            (PTupleExp) cloneNode(_tupleExp_),
            (TKeep) cloneNode(_keep_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeepTupleExp(this);
    }

    public PTupleExp getTupleExp()
    {
        return _tupleExp_;
    }

    public void setTupleExp(PTupleExp node)
    {
        if(_tupleExp_ != null)
        {
            _tupleExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tupleExp_ = node;
    }

    public TKeep getKeep()
    {
        return _keep_;
    }

    public void setKeep(TKeep node)
    {
        if(_keep_ != null)
        {
            _keep_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keep_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tupleExp_)
            + toString(_keep_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_tupleExp_ == child)
        {
            _tupleExp_ = null;
            return;
        }

        if(_keep_ == child)
        {
            _keep_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tupleExp_ == oldChild)
        {
            setTupleExp((PTupleExp) newChild);
            return;
        }

        if(_keep_ == oldChild)
        {
            setKeep((TKeep) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
