/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ALteqCmpExp extends PCmpExp
{
    private PAddExp _left_;
    private TLteq _lteq_;
    private PAddExp _right_;

    public ALteqCmpExp()
    {
    }

    public ALteqCmpExp(
        PAddExp _left_,
        TLteq _lteq_,
        PAddExp _right_)
    {
        setLeft(_left_);

        setLteq(_lteq_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new ALteqCmpExp(
            (PAddExp) cloneNode(_left_),
            (TLteq) cloneNode(_lteq_),
            (PAddExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALteqCmpExp(this);
    }

    public PAddExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PAddExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TLteq getLteq()
    {
        return _lteq_;
    }

    public void setLteq(TLteq node)
    {
        if(_lteq_ != null)
        {
            _lteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lteq_ = node;
    }

    public PAddExp getRight()
    {
        return _right_;
    }

    public void setRight(PAddExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_lteq_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_lteq_ == child)
        {
            _lteq_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PAddExp) newChild);
            return;
        }

        if(_lteq_ == oldChild)
        {
            setLteq((TLteq) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PAddExp) newChild);
            return;
        }

    }
}
