/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ALvalueBaseExp extends PBaseExp
{
    private PLvalue _lvalue_;

    public ALvalueBaseExp()
    {
    }

    public ALvalueBaseExp(
        PLvalue _lvalue_)
    {
        setLvalue(_lvalue_);

    }
    public Object clone()
    {
        return new ALvalueBaseExp(
            (PLvalue) cloneNode(_lvalue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALvalueBaseExp(this);
    }

    public PLvalue getLvalue()
    {
        return _lvalue_;
    }

    public void setLvalue(PLvalue node)
    {
        if(_lvalue_ != null)
        {
            _lvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lvalue_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lvalue_);
    }

    void removeChild(Node child)
    {
        if(_lvalue_ == child)
        {
            _lvalue_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lvalue_ == oldChild)
        {
            setLvalue((PLvalue) newChild);
            return;
        }

    }
}
