/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AManyIdentifiers extends PIdentifiers
{
    private PIdentifiers _identifiers_;
    private TComma _comma_;
    private TIdentifier _identifier_;

    public AManyIdentifiers()
    {
    }

    public AManyIdentifiers(
        PIdentifiers _identifiers_,
        TComma _comma_,
        TIdentifier _identifier_)
    {
        setIdentifiers(_identifiers_);

        setComma(_comma_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new AManyIdentifiers(
            (PIdentifiers) cloneNode(_identifiers_),
            (TComma) cloneNode(_comma_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyIdentifiers(this);
    }

    public PIdentifiers getIdentifiers()
    {
        return _identifiers_;
    }

    public void setIdentifiers(PIdentifiers node)
    {
        if(_identifiers_ != null)
        {
            _identifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifiers_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifiers_)
            + toString(_comma_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_identifiers_ == child)
        {
            _identifiers_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifiers_ == oldChild)
        {
            setIdentifiers((PIdentifiers) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
