/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AMetaHtmlbody extends PHtmlbody
{
    private TMeta _meta_;

    public AMetaHtmlbody()
    {
    }

    public AMetaHtmlbody(
        TMeta _meta_)
    {
        setMeta(_meta_);

    }
    public Object clone()
    {
        return new AMetaHtmlbody(
            (TMeta) cloneNode(_meta_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetaHtmlbody(this);
    }

    public TMeta getMeta()
    {
        return _meta_;
    }

    public void setMeta(TMeta node)
    {
        if(_meta_ != null)
        {
            _meta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _meta_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_meta_);
    }

    void removeChild(Node child)
    {
        if(_meta_ == child)
        {
            _meta_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_meta_ == oldChild)
        {
            setMeta((TMeta) newChild);
            return;
        }

    }
}
