/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AMultMultExp extends PMultExp
{
    private PMultExp _left_;
    private TMult _mult_;
    private PJoinExp _right_;

    public AMultMultExp()
    {
    }

    public AMultMultExp(
        PMultExp _left_,
        TMult _mult_,
        PJoinExp _right_)
    {
        setLeft(_left_);

        setMult(_mult_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AMultMultExp(
            (PMultExp) cloneNode(_left_),
            (TMult) cloneNode(_mult_),
            (PJoinExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultMultExp(this);
    }

    public PMultExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PMultExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TMult getMult()
    {
        return _mult_;
    }

    public void setMult(TMult node)
    {
        if(_mult_ != null)
        {
            _mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mult_ = node;
    }

    public PJoinExp getRight()
    {
        return _right_;
    }

    public void setRight(PJoinExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_mult_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_mult_ == child)
        {
            _mult_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PMultExp) newChild);
            return;
        }

        if(_mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PJoinExp) newChild);
            return;
        }

    }
}
