/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AOneFieldvalues extends PFieldvalues
{
    private PFieldvalue _fieldvalue_;

    public AOneFieldvalues()
    {
    }

    public AOneFieldvalues(
        PFieldvalue _fieldvalue_)
    {
        setFieldvalue(_fieldvalue_);

    }
    public Object clone()
    {
        return new AOneFieldvalues(
            (PFieldvalue) cloneNode(_fieldvalue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneFieldvalues(this);
    }

    public PFieldvalue getFieldvalue()
    {
        return _fieldvalue_;
    }

    public void setFieldvalue(PFieldvalue node)
    {
        if(_fieldvalue_ != null)
        {
            _fieldvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _fieldvalue_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_fieldvalue_);
    }

    void removeChild(Node child)
    {
        if(_fieldvalue_ == child)
        {
            _fieldvalue_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_fieldvalue_ == oldChild)
        {
            setFieldvalue((PFieldvalue) newChild);
            return;
        }

    }
}
