/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AOneInputs extends PInputs
{
    private PInput _input_;

    public AOneInputs()
    {
    }

    public AOneInputs(
        PInput _input_)
    {
        setInput(_input_);

    }
    public Object clone()
    {
        return new AOneInputs(
            (PInput) cloneNode(_input_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneInputs(this);
    }

    public PInput getInput()
    {
        return _input_;
    }

    public void setInput(PInput node)
    {
        if(_input_ != null)
        {
            _input_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _input_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_input_);
    }

    void removeChild(Node child)
    {
        if(_input_ == child)
        {
            _input_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_input_ == oldChild)
        {
            setInput((PInput) newChild);
            return;
        }

    }
}
