/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AOnePlugs extends PPlugs
{
    private PPlug _plug_;

    public AOnePlugs()
    {
    }

    public AOnePlugs(
        PPlug _plug_)
    {
        setPlug(_plug_);

    }
    public Object clone()
    {
        return new AOnePlugs(
            (PPlug) cloneNode(_plug_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOnePlugs(this);
    }

    public PPlug getPlug()
    {
        return _plug_;
    }

    public void setPlug(PPlug node)
    {
        if(_plug_ != null)
        {
            _plug_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plug_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_plug_);
    }

    void removeChild(Node child)
    {
        if(_plug_ == child)
        {
            _plug_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_plug_ == oldChild)
        {
            setPlug((PPlug) newChild);
            return;
        }

    }
}
