/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class APlusAddExp extends PAddExp
{
    private PAddExp _left_;
    private TPlus _plus_;
    private PMultExp _right_;

    public APlusAddExp()
    {
    }

    public APlusAddExp(
        PAddExp _left_,
        TPlus _plus_,
        PMultExp _right_)
    {
        setLeft(_left_);

        setPlus(_plus_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new APlusAddExp(
            (PAddExp) cloneNode(_left_),
            (TPlus) cloneNode(_plus_),
            (PMultExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAddExp(this);
    }

    public PAddExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PAddExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PMultExp getRight()
    {
        return _right_;
    }

    public void setRight(PMultExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_plus_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PAddExp) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PMultExp) newChild);
            return;
        }

    }
}
