/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ARadioInputtype extends PInputtype
{
    private TRadio _radio_;

    public ARadioInputtype()
    {
    }

    public ARadioInputtype(
        TRadio _radio_)
    {
        setRadio(_radio_);

    }
    public Object clone()
    {
        return new ARadioInputtype(
            (TRadio) cloneNode(_radio_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARadioInputtype(this);
    }

    public TRadio getRadio()
    {
        return _radio_;
    }

    public void setRadio(TRadio node)
    {
        if(_radio_ != null)
        {
            _radio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _radio_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_radio_);
    }

    void removeChild(Node child)
    {
        if(_radio_ == child)
        {
            _radio_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_radio_ == oldChild)
        {
            setRadio((TRadio) newChild);
            return;
        }

    }
}
