/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AShowStm extends PStm
{
    private TShow _show_;
    private PDocument _document_;
    private PReceive _receive_;
    private TSemicolon _semicolon_;

    public AShowStm()
    {
    }

    public AShowStm(
        TShow _show_,
        PDocument _document_,
        PReceive _receive_,
        TSemicolon _semicolon_)
    {
        setShow(_show_);

        setDocument(_document_);

        setReceive(_receive_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AShowStm(
            (TShow) cloneNode(_show_),
            (PDocument) cloneNode(_document_),
            (PReceive) cloneNode(_receive_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShowStm(this);
    }

    public TShow getShow()
    {
        return _show_;
    }

    public void setShow(TShow node)
    {
        if(_show_ != null)
        {
            _show_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _show_ = node;
    }

    public PDocument getDocument()
    {
        return _document_;
    }

    public void setDocument(PDocument node)
    {
        if(_document_ != null)
        {
            _document_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _document_ = node;
    }

    public PReceive getReceive()
    {
        return _receive_;
    }

    public void setReceive(PReceive node)
    {
        if(_receive_ != null)
        {
            _receive_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _receive_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_show_)
            + toString(_document_)
            + toString(_receive_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_show_ == child)
        {
            _show_ = null;
            return;
        }

        if(_document_ == child)
        {
            _document_ = null;
            return;
        }

        if(_receive_ == child)
        {
            _receive_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_show_ == oldChild)
        {
            setShow((TShow) newChild);
            return;
        }

        if(_document_ == oldChild)
        {
            setDocument((PDocument) newChild);
            return;
        }

        if(_receive_ == oldChild)
        {
            setReceive((PReceive) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
