/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ASimpleType extends PType
{
    private PSimpletype _simpletype_;

    public ASimpleType()
    {
    }

    public ASimpleType(
        PSimpletype _simpletype_)
    {
        setSimpletype(_simpletype_);

    }
    public Object clone()
    {
        return new ASimpleType(
            (PSimpletype) cloneNode(_simpletype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleType(this);
    }

    public PSimpletype getSimpletype()
    {
        return _simpletype_;
    }

    public void setSimpletype(PSimpletype node)
    {
        if(_simpletype_ != null)
        {
            _simpletype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _simpletype_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_simpletype_);
    }

    void removeChild(Node child)
    {
        if(_simpletype_ == child)
        {
            _simpletype_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_simpletype_ == oldChild)
        {
            setSimpletype((PSimpletype) newChild);
            return;
        }

    }
}
