/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ATagEndHtmlbody extends PHtmlbody
{
    private TLtSlash _ltSlash_;
    private TIdentifier _identifier_;
    private TGt _gt_;

    public ATagEndHtmlbody()
    {
    }

    public ATagEndHtmlbody(
        TLtSlash _ltSlash_,
        TIdentifier _identifier_,
        TGt _gt_)
    {
        setLtSlash(_ltSlash_);

        setIdentifier(_identifier_);

        setGt(_gt_);

    }
    public Object clone()
    {
        return new ATagEndHtmlbody(
            (TLtSlash) cloneNode(_ltSlash_),
            (TIdentifier) cloneNode(_identifier_),
            (TGt) cloneNode(_gt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATagEndHtmlbody(this);
    }

    public TLtSlash getLtSlash()
    {
        return _ltSlash_;
    }

    public void setLtSlash(TLtSlash node)
    {
        if(_ltSlash_ != null)
        {
            _ltSlash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ltSlash_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TGt getGt()
    {
        return _gt_;
    }

    public void setGt(TGt node)
    {
        if(_gt_ != null)
        {
            _gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_ltSlash_)
            + toString(_identifier_)
            + toString(_gt_);
    }

    void removeChild(Node child)
    {
        if(_ltSlash_ == child)
        {
            _ltSlash_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_gt_ == child)
        {
            _gt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_ltSlash_ == oldChild)
        {
            setLtSlash((TLtSlash) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

    }
}
