/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class ATextInputtype extends PInputtype
{
    private TText _text_;

    public ATextInputtype()
    {
    }

    public ATextInputtype(
        TText _text_)
    {
        setText(_text_);

    }
    public Object clone()
    {
        return new ATextInputtype(
            (TText) cloneNode(_text_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextInputtype(this);
    }

    public TText getText()
    {
        return _text_;
    }

    public void setText(TText node)
    {
        if(_text_ != null)
        {
            _text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _text_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_text_);
    }

    void removeChild(Node child)
    {
        if(_text_ == child)
        {
            _text_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_text_ == oldChild)
        {
            setText((TText) newChild);
            return;
        }

    }
}
