/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AVariable extends PVariable
{
    private PType _type_;
    private PIdentifiers _identifiers_;
    private TSemicolon _semicolon_;

    public AVariable()
    {
    }

    public AVariable(
        PType _type_,
        PIdentifiers _identifiers_,
        TSemicolon _semicolon_)
    {
        setType(_type_);

        setIdentifiers(_identifiers_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AVariable(
            (PType) cloneNode(_type_),
            (PIdentifiers) cloneNode(_identifiers_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariable(this);
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public PIdentifiers getIdentifiers()
    {
        return _identifiers_;
    }

    public void setIdentifiers(PIdentifiers node)
    {
        if(_identifiers_ != null)
        {
            _identifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifiers_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_type_)
            + toString(_identifiers_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

        if(_identifiers_ == child)
        {
            _identifiers_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(_identifiers_ == oldChild)
        {
            setIdentifiers((PIdentifiers) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
