/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

public final class AWhateverHtmlbody extends PHtmlbody
{
    private TWhatever _whatever_;

    public AWhateverHtmlbody()
    {
    }

    public AWhateverHtmlbody(
        TWhatever _whatever_)
    {
        setWhatever(_whatever_);

    }
    public Object clone()
    {
        return new AWhateverHtmlbody(
            (TWhatever) cloneNode(_whatever_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhateverHtmlbody(this);
    }

    public TWhatever getWhatever()
    {
        return _whatever_;
    }

    public void setWhatever(TWhatever node)
    {
        if(_whatever_ != null)
        {
            _whatever_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _whatever_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_whatever_);
    }

    void removeChild(Node child)
    {
        if(_whatever_ == child)
        {
            _whatever_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_whatever_ == oldChild)
        {
            setWhatever((TWhatever) newChild);
            return;
        }

    }
}
