/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TGtBracket extends Token
{
    public TGtBracket()
    {
        super.setText("]>");
    }

    public TGtBracket(int line, int pos)
    {
        super.setText("]>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGtBracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGtBracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGtBracket text.");
    }
}
