/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class THtmlTagStart extends Token
{
    public THtmlTagStart()
    {
        super.setText("<html>");
    }

    public THtmlTagStart(int line, int pos)
    {
        super.setText("<html>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THtmlTagStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHtmlTagStart(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change THtmlTagStart text.");
    }
}
