/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class THtml extends Token
{
    public THtml()
    {
        super.setText("html");
    }

    public THtml(int line, int pos)
    {
        super.setText("html");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THtml(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHtml(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change THtml text.");
    }
}
