/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TJoin extends Token
{
    public TJoin()
    {
        super.setText("<<");
    }

    public TJoin(int line, int pos)
    {
        super.setText("<<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TJoin(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJoin(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TJoin text.");
    }
}
