/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TKeep extends Token
{
    public TKeep()
    {
        super.setText("\\+");
    }

    public TKeep(int line, int pos)
    {
        super.setText("\\+");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeep(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeep(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeep text.");
    }
}
