/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TLtBracket extends Token
{
    public TLtBracket()
    {
        super.setText("<[");
    }

    public TLtBracket(int line, int pos)
    {
        super.setText("<[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLtBracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLtBracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLtBracket text.");
    }
}
