/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TLtSlash extends Token
{
    public TLtSlash()
    {
        super.setText("</");
    }

    public TLtSlash(int line, int pos)
    {
        super.setText("</");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLtSlash(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLtSlash(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLtSlash text.");
    }
}
