/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TRemove extends Token
{
    public TRemove()
    {
        super.setText("\\-");
    }

    public TRemove(int line, int pos)
    {
        super.setText("\\-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRemove(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRemove(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRemove text.");
    }
}
