/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

public final class TString extends Token
{
    public TString()
    {
        super.setText("string");
    }

    public TString(int line, int pos)
    {
        super.setText("string");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TString(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTString(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TString text.");
    }
}
